module.exports = {
  rules: {
    // @TODO: first-nested doesn't seem to be honored in SASS functions
    // @TODO: need a fix for two at-rules in a row
    // 'at-rule-empty-line-before': ['always', {
    //     except: [
    //         'blockless-after-same-name-blockless',
    //         'first-nested',
    //     ],
    //     ignore: ['after-comment'],
    // }],
    'at-rule-name-case': 'lower',
    'at-rule-name-space-after': 'always',
    'at-rule-semicolon-newline-after': 'always',
    'block-no-empty': true,
    'block-closing-brace-newline-after': 'always',
    'block-opening-brace-newline-after': 'always',
    'block-opening-brace-space-before': 'always',
    'color-no-invalid-hex': true,
    'declaration-no-important': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-semicolon-newline-after': 'always',
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always',
    'font-weight-notation': 'numeric',
    'length-zero-no-unit': true,
    'max-empty-lines': 1,
    'media-feature-colon-space-before': 'never',
    'media-feature-colon-space-after': 'always',
    'media-feature-name-case': 'lower',
    'media-feature-parentheses-space-inside': 'never',
    'no-extra-semicolons': true,
    'no-missing-end-of-source-newline': true,
    'number-leading-zero': 'always',
    'selector-combinator-space-before': 'always',
    'selector-combinator-space-after': 'always',
    'selector-descendant-combinator-no-non-space': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-class-case': 'lower',
    'selector-pseudo-class-parentheses-space-inside': 'never',
    'selector-pseudo-element-case': 'lower',
    'selector-pseudo-element-colon-notation': 'double',
    'rule-empty-line-before': ['always', {
        'except': [
            'first-nested',
        ],
        'ignore': ['after-comment'],
    }],
    'selector-combinator-space-after': 'always',
    'selector-combinator-space-before': 'always',
    'selector-list-comma-newline-after': 'always',
    'selector-max-specificity': '0,3,1',
    'selector-pseudo-element-colon-notation': 'double',
    // @TODO: Font names use single quotes, font lists use double quotes.
    // 'string-quotes': 'single',
    'unit-no-unknown': true,
    'value-no-vendor-prefix': true,
    // @TODO: Font names need to be in title case or whatever
    // 'value-keyword-case': 'lower',
    'value-list-comma-newline-after': 'always-multi-line',
    'value-list-comma-space-after': 'always',
  },
};
