<?php
/**
 * Get the version for a given asset.
 *
 * @NOTE
 * - This file is written with a node build script.
 * - Do not edit this file by hand.
 * - See: ./assets/config/asset-versions.js
 *
 * @param string $asset The asset name.
 * @return string The asset version.
 */
function pvd_get_asset_version( $asset ) {
	$assets = array(
		'post-css' => 'post.css',
		'post-js' => 'post.js',
		'site-css' => 'site.css',
		'site-js' => 'site.js',
	);
	return ! empty( $assets[ $asset ] ) ? $assets[ $asset ] : false;
}
